### ISSUE TITLE
Update platform/runtime to GNOME 40

### ISSUE THREAD

**Issue by x80486** [flathub/org.gnome.Dictionary#9]

**Comment by MGierz** [comment]
This issue can be closed. It is fixed with [this](https://github.com/flathub/org.gnome.Dictionary/pull/10) pullrequest.

**Comment by nedrichards** [comment]
Resolved by https://github.com/flathub/org.gnome.Dictionary/commit/69f6b92525eda95c6f75ab36b9c053381885839a
